<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="DESKTOP-ENLG37R" name="practice.Testasmainmethod" tests="8" failures="0" timestamp="17 Nov 2023 11:41:06 GMT" time="0.015" errors="1">
  <testcase name="Gatherdetails" time="0.009" classname="practice.Testasmainmethod"/>
  <testcase name="Gotobank" time="0.002" classname="practice.Testasmainmethod"/>
  <testcase name="loginDB" time="0.004" classname="practice.Testasmainmethod">
    <error type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zeroat practice.Testasmainmethod.loginDB(Testasmainmethod.java:16)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- loginDB -->
  <testcase name="loginBankAccount" time="0.000" classname="practice.Testasmainmethod">
    <skipped/>
  </testcase> <!-- loginBankAccount -->
  <testcase name="b_Enterdateofbirth" time="0.000" classname="practice.Testasmainmethod">
    <skipped/>
  </testcase> <!-- b_Enterdateofbirth -->
  <testcase name="a_EnterUsername" time="0.000" classname="practice.Testasmainmethod">
    <skipped/>
  </testcase> <!-- a_EnterUsername -->
  <testcase name="EnterPassword" time="0.000" classname="practice.Testasmainmethod">
    <skipped/>
  </testcase> <!-- EnterPassword -->
  <testcase name="ClickLogin" time="0.000" classname="practice.Testasmainmethod">
    <skipped/>
  </testcase> <!-- ClickLogin -->
</testsuite> <!-- practice.Testasmainmethod -->
